# -*- coding: utf-8 -*-
"""AI 100 Linear Regression Model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fjsF0g2GkmzJ-c1HoMOENZhWV_bXKaug
"""

import numpy as np
from sklearn.linear_model import LinearRegression

# Advertising spending ($1,000s)
X = np.array([2, 3, 4, 5, 6, 7, 8, 9]).reshape(-1, 1)

# Sales ($1,000s)
y = np.array([40, 50, 55, 65, 70, 78, 85, 95])

# Create the model
model = LinearRegression()

# Train the model
model.fit(X, y)

# Display the equation
print("Intercept:", model.intercept_)
print("Slope:", model.coef_[0])

# Predict sales when advertising = $10,000
advertising = np.array([[10]])
predicted_sales = model.predict(advertising)


print("Predicted sales: $", predicted_sales[0] * 1000)

# R-squared
print("R-squared:", model.score(X, y))

| Customer | Website Visits | Amount Spent ($) |
| -------- | -------------: | ---------------: |
| 1        |              2 |               25 |
| 2        |              3 |               32 |
| 3        |              4 |               38 |
| 4        |              5 |               45 |
| 5        |              6 |               52 |
| 6        |              7 |               58 |
| 7        |              8 |               65 |
| 8        |              9 |               70 |
| 9        |             10 |               78 |
| 10       |             11 |               85 |

import numpy as np
from sklearn.linear_model import LinearRegression

# Data from the provided table
X_visits = np.array([2, 3, 4, 5, 6, 7, 8, 9, 10, 11]).reshape(-1, 1)
y_spent = np.array([25, 32, 38, 45, 52, 58, 65, 70, 78, 85])

# Create the model
model_customer = LinearRegression()

# Train the model
model_customer.fit(X_visits, y_spent)

# Predict for the 12th customer (assuming Website Visits = 13 based on pattern)
visits_12th_customer = np.array([[13]])
predicted_spent = model_customer.predict(visits_12th_customer)

print(f"Predicted Amount Spent ($) for the 12th customer (with 13 website visits): {predicted_spent[0]:.2f}")

import numpy as np
from sklearn.linear_model import LinearRegression

# New dataset: Website Visits and Amount Spent
# Website Visits (X)
X_visits = np.array([2, 3, 4, 5, 6, 7, 8, 9, 10, 11]).reshape(-1, 1)

# Amount Spent ($) (y)
y_spent = np.array([25, 32, 38, 45, 52, 58, 65, 70, 78, 85])

# Create the model
model = LinearRegression()

# Train the model with the new data
model.fit(X_visits, y_spent)

# Display the equation components
print("\n--- Model Findings ---")
print("Intercept:", model.intercept_)
print("Slope:", model.coef_[0])
print("R-squared:", model.score(X_visits, y_spent))

# Predict amount spent for 12 website visits
visits_to_predict = np.array([[12]])
predicted_spend = model.predict(visits_to_predict)

print("\n--- Prediction ---")
print(f"Predicted amount a customer would spend if they visit the website 12 times: ${predicted_spend[0]:.2f}")

# Question for Marketing Manager:
# Would you recommend that the company try to increase the number of website visits? Why or why not?
# (Yes the company should try to increase website visits, the r^2 value is very near one meaning it has great
# (signifigance in regaurds to the dependant variable and the positive slope indicates a positive relationship)